<?php
return array (
  'qq' => 
  array (
    'status' => '1',
    'from' => 'qq',
    'show' => '腾讯',
    'des' => 'v.qq.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'http://play.23at.cn/?url=',
    'sort' => '806',
    'tip' => '无需安装任何插件',
    'id' => 'qq',
  ),
  'youku' => 
  array (
    'status' => '1',
    'from' => 'youku',
    'show' => '优酷',
    'des' => 'youku.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'http://play.23at.cn/?url=',
    'sort' => '805',
    'tip' => '无需安装任何插件',
    'id' => 'youku',
  ),
  'qiyi' => 
  array (
    'status' => '1',
    'from' => 'qiyi',
    'show' => '爱奇艺',
    'des' => 'qiyi.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'http://play.23at.cn/?url=',
    'sort' => '804',
    'tip' => '无需安装任何插件',
    'id' => 'qiyi',
  ),
  'mgtv' => 
  array (
    'status' => '1',
    'from' => 'mgtv',
    'show' => '芒果',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'http://play.23at.cn/?url=',
    'sort' => '803',
    'tip' => '无需安装任何插件',
    'id' => 'mgtv',
  ),  
  'bilibili' => 
  array (
    'status' => '1',
    'from' => 'bilibili',
    'show' => 'bilibili',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'http://play.23at.cn/?url=',
    'sort' => '802',
    'tip' => '无需安装任何插件',
    'id' => 'bilibili',
  ),  
  'sohu' => 
  array (
    'status' => '1',
    'from' => 'sohu',
    'show' => '搜狐视频',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'http://play.23at.cn/?url=',
    'sort' => '801',
    'tip' => '无需安装任何插件',
    'id' => 'sohu',
  ),
  'letv' => 
  array (
    'status' => '1',
    'from' => 'letv',
    'show' => '乐视视频',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'http://play.23at.cn/?url=',
    'sort' => '800',
    'tip' => '无需安装任何插件',
    'id' => 'letv',
  ),
);